apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
        - name: nginx-storage
          mountPath: /etc/nginx
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-storage


