apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vh02
  labels:
    app: vh02
spec:
  selector:
    matchLabels:
      app: vh02
      tier: vh02
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vh02
        tier: vh02
    spec:
      containers:
      - image: skorikkirill/wordpress2:1
        name: vh02
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: wordpress_user
        - name: WORDPRESS_DB_NAME
          value: vh02_wordpress_db
        - name: WORDPRESS_DB_PASSWORD
          value: PASSWORD
        resources:
          limits: { memory: "100Mi", cpu: "100m" }
        ports:
        - containerPort: 80
          name: vh02

