apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: vh01
spec:
  ports:
    - port: 80
  selector:
    app: vh01
    tier: vh01 
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vh01
  labels:
    app: vh01
spec:
  selector: 
    matchLabels:
      app: vh01
      tier: vh01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vh01
        tier: vh01
    spec:
      containers:
      - image: skorikkirill/wordpress1:24
        name: vh01
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: wordpress_user
        - name: WORDPRESS_DB_NAME
          value: vh01_wordpress_db
        - name: WORDPRESS_DB_PASSWORD
          value: PASSWORD
        ports:
        - containerPort: 80
          name: vh01
